### ISSUE TITLE
Hunger Overhaul preventing use of Harvestcraft's Shipping Bin

### ISSUE THREAD

**Issue by merdink** [sibomots/FooFarm#15]
![image](https://user-images.githubusercontent.com/4110814/106695046-c856af00-65a7-11eb-8987-0ac4b566b547.png)

Due to limited stacks, most of Pam's food crops is unable to be traded with the Shipping Bin for emeralds. There has to be a setting to change for that. The thing I don't know is would this impact the mod pack's difficulty too much?

**Comment by sibomots** [comment]
OK,  We can look in to this.

**Comment by Drakonas** [comment]
In my opinion the stack limitation seems kind of pointless in terms of difficulty. I don't personally think it's difficult. It's just annoying. The main thing Hunger Overhaul intends is lowering hunger amounts. If we could turn off stack limitations, I think that would be more ideal, personally.

**Comment by sibomots** [comment]
What exactly is the ask?   What is the current behavior and what is the desired behavior?

**Comment by merdink** [comment]
I want to be able to use the shipping bin with most of the foods. I am asking though if changing the stack size would affect the difficulty to the point that it's not worth the fix.

**Comment by Drakonas** [comment]
Personally, I think having Hunger Overhaul's stacks set back to vanilla would be ideal, and wouldn't affect the pack difficulty.

Hunger Overhaul is modifying the stack maximums (Ex. You can only have a max stack of 8 bread in one inventory slot, whereas vanilla the max is 64)

I think turning off this functionality in the Hunger Overhaul config would be preferred.

**Comment by merdink** [comment]
Anyone else agree with turning the stack modifying off? I'm leaning more towards that since Spice of Life keeps you from eating the same food item over and over.

**Comment by merdink** [comment]
Went ahead and just disabled Hunger Overhaul's modification of the food stack sizes. Spice of Life still presents a challenge even if you have a large stack of high foods.
