### ISSUE TITLE
Server Side Mod Suggestion: Morpheus

### ISSUE THREAD

**Issue by SamHarris2020** [sibomots/FooFarm#19]
Morpheus is a server-only mod that adds sleep voting to a forge based server. When a player sleeps, all other players in the same dimension are notified so it is easier to coordinate. Also, you can configure a ratio of players that are required to make it morning (default 50%). 

This would greatly simplify sleeping when high numbers of players are on, as currently, all players either need to leave or warp home in order to sleep. 

Lastly, since this mod is server-side only, it won't require any updates needing to be sent out to users.

**Comment by sibomots** [comment]
Good idea.  On the list.

**Comment by merdink** [comment]
Added to Version 1.3
