### ISSUE TITLE
mobGriefing - Creepers deal no damage in claims

### ISSUE THREAD

**Issue by Drakonas** [sibomots/FooFarm#2]
Not sure if this is a conflict or how the GriefDefender plugin works, but Creepers do not deal explosive damage when they explode in claims. Grief prevention, afaik, aims to prevent loss of machinery or placed blocks. I think preventing creepers from hurting you is a little much.

Is this possible to address? If not I guess we can just close the issue.

**Comment by sibomots** [comment]
Let's get some discussion on pro/con of this.

**Comment by SamHarris2020** [comment]
In my experience, I haven't used the claims system, and I haven't had any insane trouble with creepers. However, I can see a scenario where a malicious player might use creepers to circumnavigate claims and invade someone's base.

**Comment by Drakonas** [comment]
Yeah, I guess allowing them to even do damage to players in claims is a bad idea in that regards. It is possible for a griefer to probably just carefully lure one into someone's base while someone is AFK, I suppose...

**Comment by Drakonas** [comment]
Considering that players could do that, I think it best to leave as-is. I suspect if you are making claims, you have made (or are making) efforts to prevent mobs from spawning there anyways, so at that point it would be irrelevant.
