### ISSUE TITLE
Animus add-on for Blood Magic

### ISSUE THREAD

**Issue by TinySleeves** [sibomots/FooFarm#4]
It adds some additional rituals, including one that spawns peaceful mobs which could facilitate non-crop farming, especially if something like Pam's does make its way into the pack.
Also adds the ability to share soul network with other players. It seems like most people are playing the pack as a group with their friends, so this could prevent redundant work within groups.
I don't know much about running servers, but from what I can tell there's a 1.12.2 version that should be compatible with the pack.

**Comment by sibomots** [comment]
Added Animus for BloodMagic to version 1.2
