### ISSUE TITLE
Suggestion for mod: non-vanilla storage system

### ISSUE THREAD

**Issue by Drakonas** [sibomots/FooFarm#6]
I find vanilla storage to be really asenine. Not only does Minecraft prevent you from placing chests freely, but they are super small, and finding items in them is a chore when it shouldn't have to be.

For a pack called FooFarm, I think a more visual storage system would really be ideal. I don't think people should be having difficulty finding things. Some people don't have the type of memory to remember where items are, nor do the signs have the ability to label everything. And let's be honest, signs in front of chests look gaudy.

A more ideal possibility is a mod like [Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers).

This would allow a more flexible storage system, whilst looking clean and allowing integration with other mods as needed.

At the very least, having Iron Chests would really be a basis that's absolutely necessary. Perhaps having both would not be a bad idea either. (Most people go to the config and change the single-chest storage size to one size higher I believe. Base setting is kind of unbalanced.)

**Comment by sibomots** [comment]
Patched.

StorageDrawers-1.12.2-5.4.2.jar
