### ISSUE TITLE
Suggestion for mod: Just Enough Items

### ISSUE THREAD

**Issue by SamHarris2020** [sibomots/FooFarm#7]
Right now, crafting is can be confusing without easy access to recipes and better ways to manipulate resources in crafting grids. With the addition of [JEI](https://www.curseforge.com/minecraft/mc-mods/jei), we’ll be able to lookup recipes easier, and take advantage of TConstruct’s crafting grids to pull resources directly into the crafting grid using JEI.

**Comment by Drakonas** [comment]
The modpack already has JEI? I'm confused.

**Comment by Drakonas** [comment]
I see what @SamHarris2020 means. The client pack has JEI installed, but the server is missing JEI. The server needs to have JEI so that integral functions work.

![JEI missing](http://mars.whatbox.ca:42424/img/javaw_2021-01-27_08-35-13.png)

**Comment by sibomots** [comment]
Added per suggestion to 1.2
Waiting for verification.
