### ISSUE TITLE
[Bug, Permissions issue] Claims prevent other players from eating food when visiting.

### ISSUE THREAD

**Issue by Drakonas** [sibomots/FooFarm#9]
You can't use the item minecraft:bread in this claim.
Is there a way to allow you to eat in other player's claims? I died in someone else's claim since a zombie pigman came out of the nether portal and I couldn't eat to regain health.

**Comment by sibomots** [comment]
I'll check this.

**Comment by sibomots** [comment]
confirm the behavior and then I can close the ticket.
